require 'dotenv'
Dotenv.load

default_platform :ios

platform :ios do

  lane :test do
    fastlane_require 'dotenv'
    scan(
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      scheme: ENV['PROJECT_NAME'],
      output_directory: "#{ENV['CIRCLE_TEST_REPORTS']}/results.xml",
      device: "iPhone 7",
      code_coverage: true
    )
  end
end
