require 'dotenv'
Dotenv.load

default_platform :ios

platform :ios do

  lane :test do
    fastlane_require 'dotenv'
    scan(
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      scheme: "ZappAppConnector",
      output_directory: "CircleArtifacts/test-results",
      device: "iPhone 8",
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO",
      code_coverage: true
    )
  end
end
